// <auto-generated />
namespace VaWorks.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ILT_Init : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ILT_Init));
        
        string IMigrationMetadata.Id
        {
            get { return "202002212210076_ILT_Init"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
